---


- name: Get old hostname
  set_fact: old_hostname={{ ansible_hostname }}
  tags: hostname

- name: Change hostname
  hostname: name={{ inventory_hostname }}
  become_user: root
  tags: hostname

- name: Update /etc/hosts file
  replace: dest=/etc/hosts regexp={{ old_hostname }} replace={{ inventory_hostname }}
  become_user: root
  tags: hostname


